
Networkteam:
  SentryClient:
    dsn: ''
Neos:
  Flow:
    error:
      exceptionHandler:
        className: Networkteam\SentryClient\Handler\ProductionExceptionHandler
    object:
      excludeClasses:
        monolog.monolog:
          - '.*'
        sentry.sentry:
          - '.*'
